Repository lolpanda2004/Amour-Editorial-Website, pull requests merged in 2025-08, with the labels that each got.

#116 Added Impact Stories section to homepage
  amour-next-ts/src/components/ImpactStories/ImpactStories.tsx
  amour-next-ts/src/components/ImpactStories/storiesData.ts
Labels: enhancement, GSSOC, Hard

#118 The site isn't rendering and crashes ⚠️ Refresh vercel crash issue
  amour-next-ts/vercel.json
Labels: bug, GSSOC, Hard

#139 Testimonial Wall
  css/style.css
  html/Folderstructure.html
  html/about.html
  html/contributing.html
  html/features.html
  html/installation.html
  html/preview.html
  html/requirements.html
  html/techstack.html
  js/script.js
Labels: enhancement, gssoc25, level-3

#160 Fix: improved Success Stories spacing, card design, responsiveness
  amour-next-ts/src/app/success-stories/page.tsx
Labels: enhancement, gssoc25, level-3
